// <auto-generated />
using GagePopeLab5.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GagePopeLab5.Migrations
{
    [DbContext(typeof(CharacterContext))]
    partial class CharacterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GagePopeLab5.Models.Character", b =>
                {
                    b.Property<int>("characterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("characterHealth")
                        .HasColumnType("int");

                    b.Property<string>("characterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weaponName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("characterID");

                    b.HasIndex("weaponName");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GagePopeLab5.Models.Weapon", b =>
                {
                    b.Property<string>("weaponName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("weaponDamage")
                        .HasColumnType("int");

                    b.HasKey("weaponName");

                    b.ToTable("Weapons");
                });

            modelBuilder.Entity("GagePopeLab5.Models.Character", b =>
                {
                    b.HasOne("GagePopeLab5.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("weaponName");
                });
#pragma warning restore 612, 618
        }
    }
}
